apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: rdawp-bot
  name: rdawp-bot-controller
spec:
  replicas: 1
  selector:
    name: rdawp-bot
  template:
    metadata:
      labels:
        name: rdawp-bot
    spec:
      containers:
      - image: daniloaf/rdawp-bot:latest
        name: rdawp-bot
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: http-server
        env:
          - name: MONGODB_URI
            valueFrom:
              secretKeyRef:
                name: ot-keys
                key: MONGODB_URI_RDAWP
          - name: TELEGRAM_BOT_TOKEN
            valueFrom:
              secretKeyRef:
                name: ot-keys
                key: TELEGRAM_RDAWP_BOT_TOKEN
